### ISSUE TITLE
[명세] BE API & ERD

### ISSUE THREAD

**Issue by djlim98** [osamhack2022/APP_Meerkat_IQDan#20]

**Comment by hyelie** [comment]
[ERD](https://github.com/osamhack2022/APP_Meerkat_IQDan/wiki/ERD)

작업 끝나면 ERD 확인 부탁합니다.

@seho0808 @djlim98 @exqt

**Comment by hyelie** [comment]
[socket event 명세 참고 1](https://github-wiki-see.page/m/boostcamp-2020/Project12-B-Slack-Web/wiki/socket.io-%EB%AA%85%EC%84%B8%EC%84%9C)

[socket event 명세 참고 2](https://www.asyncapi.com/blog/socketio-part2)

**Comment by hyelie** [comment]
@djlim98 @seho0808 @exqt 
API 명세 socket event까지 명세 끝났습니다. 확인 부탁합니다.

[API 명세 링크](https://github.com/osamhack2022/APP_Meerkat_IQDan/wiki/API-Specification)

### 변경점
- CRUD 색깔 gitbook과 동일하게 변경
- index 맞지 않았던 점(###, ####, #####, ######가 섞여 있었던 점) 수정
- socket event 명세 추가
