### ISSUE TITLE
FE/BE 이상 무 기능

### ISSUE THREAD

**Issue by hyelie** [osamhack2022/APP_Meerkat_IQDan#220]
### 이상무 로직

보낸 사람이 특정 방법을 써서 (send 아래에 버튼 추가?) 보내면 본인은 메시지창 아래에 '통계 보기' 버튼이 생기고, 타인은 quick reply처럼 버튼이 나옴.
본인은 통계 보기 버튼을 누르면 읽은 사람 목록처럼 응답한사람 목록, 응답 안한사람 목록을 BE에서 받아오고,
다른 사람은 그 버튼을 클릭하면 서버로 요청을 보냄.

**Comment by seho0808** [comment]
구현방법 1. 보낼때 text앞에 "[이상무]"를 붙여서 서버에 저장하고 읽어올 때 "[이상무]안녕얘들아" 이런식으로 앞에 이상무 있으면 밑에 버튼 두 개 (이상무 / 특이사항) 이렇게 두 가지 옵션을 줌. 이상무 통계 집계자 입장에서 보면 버튼이 아닌 "이상무 통계"라고 나오고 누르면 안에 세개의 상단 탭("이상무"/"특이사항"/"안읽은 사람")이렇게 있음. 특이사항일 경우 상태메시지마냥 밑에 각자가 보고할 때 적은거 뭐적혀있음.

구현방법 2. 보낼때 따로 새로운 테이블에 특정 메세지 아이디가 이상무임을 표시해주고 메세지 받을 때에는 지금 화면에 표시되는 모든 메세지 한번 id 마다 이상무인지 확인하는 api짜기.

**Comment by hyelie** [comment]
### 분석
- quick reply의 attribute는 다음과 같음.
    - title은 보이는 값
    - value는 전달되는 값
    - messageId는 해당 quick reply가 붙어있는 message id
- 따라서 버튼을 누르면 BE로 요청이 가게.

### 문제는 그거임.
1) quick reply를 어떻게 보내게 할 것인지 - 찾아봐야 함. 버튼으로 하는 게 좋을 것 같은데...
    - 서버에 올릴 떄도 quick reply가 들어간 상태로 올라가야 함. 올라가는지 체크. socket 전송도 마찬가지.
2) 보낸 사람은 qucik reply를 보이지 않게 하고, 해당 message id의 통계 창을 띄워주어야 하고
    - message의 sender와 user id를 검사해서 본인이면 이상무 통계를 띄워줌.
    - 본인이 아니면 quick reply가 보임.(이상무, 특이사항)
3) 이상무, 특이사항을 누르면 서버에 요청 가서 해당 message id에 저장하게 하기.
    - 서버에서는 해당 msg 안 읽은 사람, 이상무 클릭한 사람, 특이사항을 저장하게 하고, 받아올 수 있어야 함.

**Comment by hyelie** [comment]
로직 작성 완료, UI만 다듬으면 됨.

파일은
./pages 내의
AllClearStatistics/*
ReportAllClear
MyAllClearReport
5개 보면 됨.

지금은 [이상무 보고] 이용 시 [통계 확인, 보고, 보고내용 확인] 3개 다 있는데 UI 다 다듬어지고 테스팅 끝나면 [통계 확인]은 작성한 사람만, [보고, 보고내용 확인]은 작성한 사람 빼고 보여줄 것임.

**Comment by hyelie** [comment]
[보고내용 확인]을 없애고, 보고한 내용이 있는 경우 [보고하기] 탭에 보고했던 내용이 들어오고, "제출하기" 대신 "수정하기" 버튼으로 변경.
