### ISSUE TITLE
FE/BE 읽은 사람

### ISSUE THREAD

**Issue by hyelie** [osamhack2022/APP_Meerkat_IQDan#224]

**Comment by hyelie** [comment]
시간 따로 뺐고, UI 정리만 하면 될 듯.

**Comment by hyelie** [comment]
BE도 다함.

**Comment by seho0808** [comment]
시계 바꾸는 법
https://github.com/FaridSafi/react-native-gifted-chat/issues/1655#issuecomment-590246671
=> 이걸로 눈알 말풍선 안에 시간 옆에 붙이고 밖에 있는 시간은 없애는게 예쁠듯?
그리고 ShowReaderViewer처럼 막 props들어오는거 아니면 컴포넌트 밖에 만들어야 효율 좋음.
왜냐하면 state가 아닌 평문으로된 선언은 다른 state 아무거나 바뀌면 무조건 다시 다돔. 그래서
const MyBubble 아래로 빼놓음.
@hyelie

**Comment by hyelie** [comment]
넹 일단 작업은 끝냈는데 ChatroomPage의 ChatTime부분, 채팅이 왼쪽에 있냐 오른쪽에 있냐에 따라서 생긴 게 달라져야 해서 if문으로 분기 해 뒀음. 좀 더러우니까 나중에 리팩토링 해야 함.
