### ISSUE TITLE
FE/BE API 호출 예제 제작

### ISSUE THREAD

**Issue by hyelie** [osamhack2022/APP_Meerkat_IQDan#42]

**Comment by seho0808** [comment]
https://kyome.tistory.com/150

**Comment by hyelie** [comment]
우여곡절

1. mixed content error
https server에서 http로 요청하면 안됨.
 
2. 서버에 SSL 적용
그래서 서버에 ssl을 적용하려 했음. 기존 nginx에 적용되고 있던 인증서를 그대로 express에 적용하려 했으나 문제 발생.

node.js는 8081에 배포, nginx는 8082에 들어오는 것을 ssl 설정해서 8081로 포트포워딩하는 방식 채용

3. trust anchor for certification path not found 오류
openssl을 이용해 새 인증서를 발급받고 그걸 node server에 적용함으로써 해결했음. 개발 서버의 local은 해당 서버의 ssl이 적용되어서 그런 게 아닐까... 추측.
 
[openssl 적용법](https://freestrokes.tistory.com/154)
