### ISSUE TITLE
BE/chatRoom 구현

### ISSUE THREAD

**Issue by djlim98** [osamhack2022/APP_Meerkat_IQDan#64]

**Comment by seho0808** [comment]
1. 친구들 모두 보여주는 API 생성
2. E2EE를 위한 Private Key를 회원가입할 때 프런트에서 생성해서 백엔드와 Async에 Public Private key를 저장하도록 수정.
3. 1대1 채팅용 API + 프런트작업
4. 여러명 채팅용 API + 프런트작업

**Comment by hyelie** [comment]
### raw query는 짰음
생각하다 보니까, 이런 종류의 쿼리는 intersect가 들어가야 함. 무조건임. select와 group by, having으로만 짤 수는 없음.
```
select c.chatroomId
    from Chatroom c join UsersOnChatrooms p on c.chatroomId=p.chatroomId
    where c.type = 'single' and p.userId = ${userId}
    
    INTERSECT
    
select c.chatroomId
    from Chatroom c join UsersOnChatrooms p on c.chatroomId=p.chatroomId
    where c.type = 'single' and p.userId = ${targetUserId};
```

아니면 subquery IN을 활용해서 짜도 될듯?
```
select c.chatroomId
      from Chatroom c join UsersOnChatrooms p on c.chatroomId=p.chatroomId
      where p.userId = ${userId} AND c.chatroomId IN (
            select c.chatroomId
            from Chatroom c join UsersOnChatrooms p on c.chatroomId=p.chatroomId
            where c.type = 'single' and p.userId = ${targetUserId}
      );
```

### for문으로 돌릴 수 있게도 짰음
prisma에서 or은 |로 묶는 게 아니라 OR이라는 별도의 연산자를 사용해 줘야 함.
const chatRooms = await this.chatRoom.findMany({
      where:{
        type: ChatroomType.SINGLE,
      },
      select:{
        users:{
          where:{
            OR:[
              {
                userId: targetUserId
              },
              {
                userId: userId
              }
            ],
          },
          select:{
            chatroomId: true,
            userId: true,
          },          
        }
      }
    });
