### ISSUE TITLE
FEBE/message 구현

### ISSUE THREAD

**Issue by djlim98** [osamhack2022/APP_Meerkat_IQDan#65]
세부사항
foreground의 경우 - socket 통신
background의 경우 - push notification만 줌
offline의 경우 - 아무것도 하지 않음. online으로 전환될 때 읽지 않은 메시지를 한 번에 보내주기.

GCM의 경우에 offline이라면 알아서 message queue에 넣고 발송해 준다고 한다. 
~~또 socketio에 있는 volatile이라는 기능도 있는데.. 고민해 봐야 할 듯. [링크](https://socket.io/docs/v3/emitting-events/~~
volatile의 경우 메시지 유실 가능성이 커서 유기.

**Comment by seho0808** [comment]
[공식문서](https://socket.io/docs/v3/namespaces/) 에 나온것 처럼 그냥 2번으로 하는게 편할듯.
내 생각엔 만약 XSS로 다른 방 access할 시도라면 두 가지 모두 취약하긴한듯? 
그나마 확실한 방법은 채팅방 마다 채팅방 이름 + id로 해싱해서 해시값을 또 고유로 갖고 있게해서
그 해시값을 namespaces/해시값 이런식으로 액세스하면 brute force XSS로 못 뚫을듯?

**Comment by seho0808** [comment]
[또다른 해결방법](https://stackoverflow.com/questions/23520019/how-can-i-refuse-some-user-joins-the-same-room-in-socket-io)으로는 join할 때 유저 토큰 확인하는 것도 가능함.

**Comment by seho0808** [comment]
내가 찾은 방법 정리
방법 1. 여러 namespace 지정
```
const workspaces = io.of(/^\/\w+$/);

workspaces.on("connection", socket => {
  const workspace = socket.nsp;

  workspace.emit("hello");
});
```
출처: [공식문서](https://socket.io/docs/v4/namespaces/)
단점: 아무나 랜덤 값 찾으면 들어올수는 있음.

방법 2. 한 개의 namespace 에서 토큰 검증
```
const adminNamespace = io.of("/admin");

adminNamespace.use((socket, next) => {
  // ensure the user has sufficient rights
  // 여기서 토큰 검증하고 그 토큰에 있는 유저 이름이 해당 채팅방에 db에 저장되어있는지 확인.
  next();
});

adminNamespace.on("connection", socket => {
  socket.on("delete user", () => {
    // ...
  });
});
```
출처: [공식문서](https://socket.io/docs/v4/namespaces/)
참고: [Auth사용예시](https://stackoverflow.com/questions/23520019/how-can-i-refuse-some-user-joins-the-same-room-in-socket-io)
단점: 구현이 조금 귀찮음. 대신 제일 나은 솔루션인듯..? + 공식문서에서는 auth token 인증 방법이 직접적으로 명시되어있지는
않고 기능별로 나눌 때 이 방법을 쓰라고 함.

방법 3. namespace 하나로 chat 쓰고 그 뒤에 붙는 route를 해싱.
채팅방 마다 채팅방 이름 + id로 해싱해서 해시값을 또 고유로 갖고 있게해서
그 해시값을 namespaces/해시값 이런식으로 액세스.
해시값 굳이 안쓰더라도 방법 2 처럼 on connect 전에 미들웨어로 auth token 검증하면 상관없을듯.

단점: 구현이 귀찮음.

**Comment by hyelie** [comment]
socketio를 react native context에 붙여넣었음. 
또한, socket io event를 emit할 때는 isSocketConnected가 true일때만 사용해야 함.
 - 연결되지 않았을 때 event를 emit해 버리면, 연결 될 때 까지 전부 다 message queue에 들어감. 
 - event가 몇개 없다면 괜찮겠지만 많아지면 램을 오지게 잡아먹을 것.
 - 또 인터넷이 연결되지 않았을 때에 대한 예외처리를 하기 쉬워지기 때문에 이렇게 사용하는 것을 추천.

```
  const {socket, isSocketConnected} = useContext(SocketContext);
  if(isSocketConnected){
    socket.timeout(5000).emit(EVENT_NAME, EVENT_BODY);
    socket.timeout(5000).emit(EVENT_NAME, EVENT_BODY);
  }
```

**Comment by hyelie** [comment]
socket 다붙였음. event 작업시작.

**Comment by hyelie** [comment]
지금 TODO
- 첫 접속 시 밀린 채팅기록 DB에서 받아오기
- 채팅 읽은사람 구현
- 채팅 보내면 DB에 저장하기

**Comment by seho0808** [comment]
메시지 로컬 저장 로직:

1. 방 밖에 있을 떄는 일단 메시지를 고민하지 않아도됨. 방에 들어간 상태일 때만 메시지를 저장하거나 로컬 메시지를 가져오기.
2. last read 시점으로부터 새로운 메시지만 서버에서 읽어올 것임. 그렇기 때문에, 과거의 채팅은 싹다 무시하면됨. 새로운 채팅이 아닌 모든 옛날 채팅은 로컬에서 가져오고, 없으면 무시. 그리고 새로운 채팅은 모두 서버에서 fetch 후 로컬에 저장.
3.

**Comment by seho0808** [comment]
## 다음 할일
- 유저 붙이기 => 현재 티켓으로 넘버링. #187 
- E2EE 붙이기 => E2ee 티켓으로 넘버링.
- 채팅방 암호화 붙이기 => 채팅방 암호화 티켓으로 넘버링.

추가 티켓들
- 읽은 사람 UI만
- 
- 상급자 기능
- 이상무 UI만
- 이모지 UI만

**Comment by hyelie** [comment]
E2EE 속도 느린 것 -> console.log 찍어봤는데, console log받아오는 속도는 꽤 빠름. 거의 보내자마자 바로 옴. 예측했던 대로 복호화 속도가 좀 느린 듯.

개선 관련해서 
 - 메시지 전송 버튼을 누르면 onSend로 채팅방에 바로 뿌린다
 - 서버에서는 io.to().emit()이 아니라, socket.broadcast()를 해서 전송자 빼고 보내준다
라고 이야기 했었는데, 코드를 좀 읽어본 결과 생각을 조금 해 봐야 할 듯?

 현재 채팅방에서 사용하고 있는 iMessage의 _id값을 서버에서 받아온 Message.messageId값으로 사용하고 있고, 이 값으로 메시지들의 순서를 정하고 식별하는 역할을 함. 꼭 넣어줘야 하는 값이기도 하고.

 그래서 생각해본 후보들은
 - 1. 하책. 현재 message 중에서 제일 마지막 _id값 +1로 onSend message를 설정하고, 서버에서 io.to().emit()으로 값을 받아오면 해당 메시지를 대체
     - 근데 이래버리면 message list가 비었을 경우 문제가 발생함 -> 그냥 999999같은 INF값으로 설정할 수도..? 근데 좀 더럽긴 함.
 - 2. 중책. '보낸 메시지 내용'을 저장할 임시 공간 temp를 하나 만들고, 메시지 발송할 때 temp에 그 값 저장, socket으로 iMessageDto를 받아오면 _id값이랑 temp에 있는 값을 꺼내서 onSend를 하고, temp를 null로 만들면 될 것 같음.
 - 3. 이건 조치한 내용인데, useMessage.tsx의 170번줄, 171번줄의 순서를 바꾸었음. 기존에는 메시지를 로컬에 저장, 이후에 onSend를 호출해서 view에 띄워주는데, 읽어보니 로컬에 저장하는 로직에 await가 꽤 많이 붙어있고 asyncStorage에 값 넣는 것도 [기존 메시지 리스트 + 받아온 메시지 전체]가 들어가니 꽤 시간이 걸릴 것 같다고 판단되어 일단 순서를 바꾸었음. 속도가 나오는지는 내일 테스트 해 봐야 알 듯.

**Comment by hyelie** [comment]
### user 붙이기
  ```
  usersInfo.map((elem:User)=>{
    elem.userId;
    elem.name;
  });
  ```
  이렇게 순회해서 userId를 key로, {_id:elem.userId, name:elem.name}를 value로 가지는
  map을 하나 만들고, getNewMessagesFromSocket에서 userId key로 찾아오면 되고,
  제일 밑에 GiftedChat 설정할 때도 current user Id에 해당하는 것 넣어주면 되고,
  useMessage parameter에 넣어서 바로 갖다쓸 수도 있을 듯.

**Comment by seho0808** [comment]
지금 메세지 많으면 가장 아래까지 안가는듯함

**Comment by hyelie** [comment]
### 이상무 로직

보낸 사람이 특정 방법을 써서 (send 아래에 버튼 추가?) 보내면 본인은 메시지창 아래에 '통계 보기' 버튼이 생기고, 타인은 quick reply처럼 버튼이 나옴.
본인은 통계 보기 버튼을 누르면 읽은 사람 목록처럼 응답한사람 목록, 응답 안한사람 목록을 BE에서 받아오고,
다른 사람은 그 버튼을 클릭하면 서버로 요청을 보냄.
